name: Deploy .NET Backend to VPS

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Publish .NET project
      run: |
        cd dotnet-api
        dotnet publish -c Release -o publish

    - name: Clean old backend on VPS
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.VPS_HOST }}
        username: root
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          rm -rf /var/www/backend/*

    - name: Deploy to VPS via SCP
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.VPS_HOST }}
        username: root
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        source: "dotnet-api/publish/**"
        target: "/var/www/backend"
        strip_components: 1

    - name: Restart backend service
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.VPS_HOST }}
        username: root
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          systemctl restart dotnet-backend.service
